package com.example.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.domain.Bookmarks;
import com.example.domain.BookmarksExample;

@Mapper
public interface BookmarksMapper {
	
	//追加
	@Select({
	    "select * from bookmarks where schedule_id = #{schedule_id}"
	})
	List<Bookmarks> selectBySchedule_id(Integer schedule_id);
	
	@Select({
	    "select * from bookmarks WHERE user_id = #{user_id} AND schedule_id = #{schedule_id}"
	})
	List<Bookmarks> selectBySchedule_idANDUser_id(Integer user_id, Integer schedule_id);
	
	@Insert({
		"insert into bookmarks (user_id,schedule_id) values (#{user_id}, #{schedule_id})"
	})
	 int bookmarkInsert(@Param("user_id") Integer user_id, @Param("schedule_id") Integer schedule_id);
	
	@Delete({
		"DELETE FROM bookmarks WHERE user_id = #{user_id} AND schedule_id = #{schedule_id}"
	})
	int bookmarkDelete(@Param("user_id") Integer user_id, @Param("schedule_id") Integer schedule_id);
	//ここまで
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    long countByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int deleteByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Delete({
        "delete from bookmarks",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Insert({
        "insert into bookmarks (id, user_id, ",
        "schedule_id)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{scheduleId,jdbcType=INTEGER})"
    })
    int insert(Bookmarks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int insertSelective(Bookmarks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    List<Bookmarks> selectByExample(BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Select({
        "select",
        "id, user_id, schedule_id",
        "from bookmarks",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.mybatis.mapper.BookmarksMapper.BaseResultMap")
    Bookmarks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExampleSelective(@Param("row") Bookmarks row, @Param("example") BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExample(@Param("row") Bookmarks row, @Param("example") BookmarksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByPrimaryKeySelective(Bookmarks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookmarks
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Update({
        "update bookmarks",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "schedule_id = #{scheduleId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Bookmarks row);
}