package com.example.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.domain.Relationships;
import com.example.domain.RelationshipsExample;

@Mapper
public interface RelationshipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    long countByExample(RelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int deleteByExample(RelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Delete({
        "delete from relationships",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Insert({
        "insert into relationships (id, schedule_id, ",
        "use_scene_id)",
        "values (#{id,jdbcType=INTEGER}, #{scheduleId,jdbcType=INTEGER}, ",
        "#{useSceneId,jdbcType=INTEGER})"
    })
    int insert(Relationships row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int insertSelective(Relationships row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    List<Relationships> selectByExample(RelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Select({
        "select",
        "id, schedule_id, use_scene_id",
        "from relationships",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.mybatis.mapper.RelationshipsMapper.BaseResultMap")
    Relationships selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExampleSelective(@Param("row") Relationships row, @Param("example") RelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExample(@Param("row") Relationships row, @Param("example") RelationshipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByPrimaryKeySelective(Relationships row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Update({
        "update relationships",
        "set schedule_id = #{scheduleId,jdbcType=INTEGER},",
          "use_scene_id = #{useSceneId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Relationships row);
}