package com.example.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.domain.Schedules;
import com.example.domain.SchedulesExample;

@Mapper
public interface SchedulesMapper {
	//追加
	@Select({
	    "select * from schedules where user_id = #{user_id}"
	})
	List<Schedules> selectAllByUserId(Integer user_id);
	
	@Select({
	    "select * from schedules where id = #{id}"
	})
	List<Schedules> selectById(Integer id);
	
	//ここまで
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    long countByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int deleteByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Delete({
        "delete from schedules",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Insert({
        "insert into schedules (id, user_id, ",
        "date, park, holiday, ",
        "schedule)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{date,jdbcType=DATE}, #{park,jdbcType=INTEGER}, #{holiday,jdbcType=BIT}, ",
        "#{schedule,jdbcType=LONGVARCHAR})"
    })
    int insert(Schedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int insertSelective(Schedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    List<Schedules> selectByExampleWithBLOBs(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    List<Schedules> selectByExample(SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Select({
        "select",
        "id, user_id, date, park, holiday, schedule",
        "from schedules",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.mybatis.mapper.SchedulesMapper.ResultMapWithBLOBs")
    Schedules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExampleSelective(@Param("row") Schedules row, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Schedules row, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByExample(@Param("row") Schedules row, @Param("example") SchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    int updateByPrimaryKeySelective(Schedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Update({
        "update schedules",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "date = #{date,jdbcType=DATE},",
          "park = #{park,jdbcType=INTEGER},",
          "holiday = #{holiday,jdbcType=BIT},",
          "schedule = #{schedule,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Schedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedules
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    @Update({
        "update schedules",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "date = #{date,jdbcType=DATE},",
          "park = #{park,jdbcType=INTEGER},",
          "holiday = #{holiday,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Schedules row);
}