package com.example.domain;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Bookmarks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
	@Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.user_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookmarks.schedule_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    private Integer scheduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.id
     *
     * @return the value of bookmarks.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.id
     *
     * @param id the value for bookmarks.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.user_id
     *
     * @return the value of bookmarks.user_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.user_id
     *
     * @param userId the value for bookmarks.user_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookmarks.schedule_id
     *
     * @return the value of bookmarks.schedule_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookmarks.schedule_id
     *
     * @param scheduleId the value for bookmarks.schedule_id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }
}