package com.example.domain;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class UseScenes {
	//追加
    @Override
    public String toString() {
        return useSceneName;
    }
    //ここまで
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_scenes.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
	@Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_scenes.use_scene_name
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    private String useSceneName;
    private boolean selected;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_scenes.id
     *
     * @return the value of use_scenes.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_scenes.id
     *
     * @param id the value for use_scenes.id
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_scenes.use_scene_name
     *
     * @return the value of use_scenes.use_scene_name
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public String getUseSceneName() {
        return useSceneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_scenes.use_scene_name
     *
     * @param useSceneName the value for use_scenes.use_scene_name
     *
     * @mbg.generated Thu Jun 08 09:58:52 JST 2023
     */
    public void setUseSceneName(String useSceneName) {
        this.useSceneName = useSceneName == null ? null : useSceneName.trim();
    }
    
    public boolean isSelected() {
    	return selected;
    }
    
    public void setSelected(boolean selected) {
    	this.selected = selected;
    }

}